apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classification-deployment
  labels:
    poc: text-classification
spec:
  replicas: 1
  selector:
    matchLabels:
      poc: text-classification
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        poc: text-classification
    spec:
      containers:
      - name: text-classification
        image: adepena/text-classification:dev.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: text-classification-service
  labels:
    poc: text-classification
spec:
  type: ClusterIP
  selector:
    poc: text-classification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80        