apiVersion: v1
kind: Service
metadata:
  name: text-classification-service
  labels:
    poc: text-classification
spec:
  type: NodePort
  selector:
    poc: text-classification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80